# SPDX-FileCopyrightText: 2025 Lukas <lukasku@proton.me>
# SPDX-License-Identifier: MPL-2.0

[package]
name = "pr"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = [
    "crates/pr-client",
    "crates/pr-server",
    "crates/common"
]
