[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
bincode = "2.0.1"
tokio = { version = "1.45.1", features = ["full"] }
aes-gcm = "0.10.3"
aes = "0.8.4"
aead = "0.5.2"
rand = "0.8"
